elasticsearch:
  image: elasticsearch:1.5.2
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"
  expose:
    - "9200"
  volumes:
    - /var/docker/elasticsearch:/usr/share/elasticsearch/config
db:
  image: kartoza/postgis
  ports:
    - "5432:5432"
  expose:
    - "5432"
  volumes:
    - /var/docker/postgres:/var/lib/postgresql/data
redis:
  image: redis
  ports:
    - "6379:6379"
  expose:
    - "6379"
  volumes:
    - /var/docker/postgres:/data